{% set version = "1.0" %}

package:
  name: gralign-tools
  version: {{ version }}

source:
  url: https://github.com/erikrikarddaniel/gralign-tools/archive/v{{ version }}.tar.gz

build:
  noarch: generic

requirements:
  build:
    - python
    - setuptools

  run:
    - ruby >=2.7
